export interface ModelEntry {
  marketName: string;
  brand: string;
}

const db: Record<string, ModelEntry> = {
  // ===== SAMSUNG =====
  'SM-S928B': { marketName: 'Galaxy S24 Ultra', brand: 'Samsung' },
  'SM-S928U': { marketName: 'Galaxy S24 Ultra', brand: 'Samsung' },
  'SM-S926B': { marketName: 'Galaxy S24+', brand: 'Samsung' },
  'SM-S926U': { marketName: 'Galaxy S24+', brand: 'Samsung' },
  'SM-S921B': { marketName: 'Galaxy S24', brand: 'Samsung' },
  'SM-S921U': { marketName: 'Galaxy S24', brand: 'Samsung' },
  'SM-S918B': { marketName: 'Galaxy S23 Ultra', brand: 'Samsung' },
  'SM-S918U': { marketName: 'Galaxy S23 Ultra', brand: 'Samsung' },
  'SM-S916B': { marketName: 'Galaxy S23+', brand: 'Samsung' },
  'SM-S911B': { marketName: 'Galaxy S23', brand: 'Samsung' },
  'SM-S908B': { marketName: 'Galaxy S22 Ultra', brand: 'Samsung' },
  'SM-S908U': { marketName: 'Galaxy S22 Ultra', brand: 'Samsung' },
  'SM-S906B': { marketName: 'Galaxy S22+', brand: 'Samsung' },
  'SM-S901B': { marketName: 'Galaxy S22', brand: 'Samsung' },
  'SM-G998B': { marketName: 'Galaxy S21 Ultra', brand: 'Samsung' },
  'SM-G996B': { marketName: 'Galaxy S21+', brand: 'Samsung' },
  'SM-G991B': { marketName: 'Galaxy S21', brand: 'Samsung' },
  'SM-G988B': { marketName: 'Galaxy S20 Ultra', brand: 'Samsung' },
  'SM-G986B': { marketName: 'Galaxy S20+', brand: 'Samsung' },
  'SM-G981B': { marketName: 'Galaxy S20', brand: 'Samsung' },
  'SM-G985F': { marketName: 'Galaxy S20+', brand: 'Samsung' },
  'SM-G980F': { marketName: 'Galaxy S20', brand: 'Samsung' },
  'SM-G975F': { marketName: 'Galaxy S10+', brand: 'Samsung' },
  'SM-G973F': { marketName: 'Galaxy S10', brand: 'Samsung' },
  'SM-G970F': { marketName: 'Galaxy S10e', brand: 'Samsung' },
  'SM-G960F': { marketName: 'Galaxy S9', brand: 'Samsung' },
  'SM-G965F': { marketName: 'Galaxy S9+', brand: 'Samsung' },
  'SM-G950F': { marketName: 'Galaxy S8', brand: 'Samsung' },
  'SM-G955F': { marketName: 'Galaxy S8+', brand: 'Samsung' },
  'SM-S938B': { marketName: 'Galaxy S25 Ultra', brand: 'Samsung' },
  'SM-S938U': { marketName: 'Galaxy S25 Ultra', brand: 'Samsung' },
  'SM-S936B': { marketName: 'Galaxy S25+', brand: 'Samsung' },
  'SM-S936U': { marketName: 'Galaxy S25+', brand: 'Samsung' },
  'SM-S931B': { marketName: 'Galaxy S25', brand: 'Samsung' },
  'SM-S931U': { marketName: 'Galaxy S25', brand: 'Samsung' },
  'SM-S711B': { marketName: 'Galaxy S23 FE', brand: 'Samsung' },
  'SM-G781B': { marketName: 'Galaxy S20 FE', brand: 'Samsung' },
  'SM-G990B': { marketName: 'Galaxy S21 FE', brand: 'Samsung' },
  'SM-F966B': { marketName: 'Galaxy Z Fold7', brand: 'Samsung' },
  'SM-F766B': { marketName: 'Galaxy Z Flip7', brand: 'Samsung' },
  'SM-F956B': { marketName: 'Galaxy Z Fold6', brand: 'Samsung' },
  'SM-F946B': { marketName: 'Galaxy Z Fold5', brand: 'Samsung' },
  'SM-F936B': { marketName: 'Galaxy Z Fold4', brand: 'Samsung' },
  'SM-F926B': { marketName: 'Galaxy Z Fold3', brand: 'Samsung' },
  'SM-F916B': { marketName: 'Galaxy Z Fold2', brand: 'Samsung' },
  'SM-F741B': { marketName: 'Galaxy Z Flip6', brand: 'Samsung' },
  'SM-F731B': { marketName: 'Galaxy Z Flip5', brand: 'Samsung' },
  'SM-F721B': { marketName: 'Galaxy Z Flip4', brand: 'Samsung' },
  'SM-F711B': { marketName: 'Galaxy Z Flip3', brand: 'Samsung' },
  'SM-A556B': { marketName: 'Galaxy A55', brand: 'Samsung' },
  'SM-A546B': { marketName: 'Galaxy A54', brand: 'Samsung' },
  'SM-A546E': { marketName: 'Galaxy A54', brand: 'Samsung' },
  'SM-A536B': { marketName: 'Galaxy A53', brand: 'Samsung' },
  'SM-A536E': { marketName: 'Galaxy A53', brand: 'Samsung' },
  'SM-A526B': { marketName: 'Galaxy A52', brand: 'Samsung' },
  'SM-A525F': { marketName: 'Galaxy A52', brand: 'Samsung' },
  'SM-A516B': { marketName: 'Galaxy A51 5G', brand: 'Samsung' },
  'SM-A515F': { marketName: 'Galaxy A51', brand: 'Samsung' },
  'SM-A356B': { marketName: 'Galaxy A35', brand: 'Samsung' },
  'SM-A346B': { marketName: 'Galaxy A34', brand: 'Samsung' },
  'SM-A336B': { marketName: 'Galaxy A33', brand: 'Samsung' },
  'SM-A256B': { marketName: 'Galaxy A25', brand: 'Samsung' },
  'SM-A246B': { marketName: 'Galaxy A24', brand: 'Samsung' },
  'SM-A236B': { marketName: 'Galaxy A23', brand: 'Samsung' },
  'SM-A235F': { marketName: 'Galaxy A23', brand: 'Samsung' },
  'SM-A226B': { marketName: 'Galaxy A22 5G', brand: 'Samsung' },
  'SM-A225F': { marketName: 'Galaxy A22', brand: 'Samsung' },
  'SM-A156B': { marketName: 'Galaxy A15', brand: 'Samsung' },
  'SM-A155F': { marketName: 'Galaxy A15', brand: 'Samsung' },
  'SM-A146B': { marketName: 'Galaxy A14', brand: 'Samsung' },
  'SM-A145F': { marketName: 'Galaxy A14', brand: 'Samsung' },
  'SM-A136B': { marketName: 'Galaxy A13 5G', brand: 'Samsung' },
  'SM-A135F': { marketName: 'Galaxy A13', brand: 'Samsung' },
  'SM-A127F': { marketName: 'Galaxy A12', brand: 'Samsung' },
  'SM-A125F': { marketName: 'Galaxy A12', brand: 'Samsung' },
  'SM-A057F': { marketName: 'Galaxy A05s', brand: 'Samsung' },
  'SM-A055F': { marketName: 'Galaxy A05', brand: 'Samsung' },
  'SM-A047F': { marketName: 'Galaxy A04s', brand: 'Samsung' },
  'SM-A045F': { marketName: 'Galaxy A04', brand: 'Samsung' },
  'SM-A037F': { marketName: 'Galaxy A03s', brand: 'Samsung' },
  'SM-A035F': { marketName: 'Galaxy A03', brand: 'Samsung' },
  'SM-A566B': { marketName: 'Galaxy A56', brand: 'Samsung' },
  'SM-A366B': { marketName: 'Galaxy A36', brand: 'Samsung' },
  'SM-A266B': { marketName: 'Galaxy A26', brand: 'Samsung' },
  'SM-A166B': { marketName: 'Galaxy A16', brand: 'Samsung' },
  'SM-A165F': { marketName: 'Galaxy A16', brand: 'Samsung' },
  'SM-A066B': { marketName: 'Galaxy A06', brand: 'Samsung' },
  'SM-A065F': { marketName: 'Galaxy A06', brand: 'Samsung' },
  'SM-A325F': { marketName: 'Galaxy A32', brand: 'Samsung' },
  'SM-A326B': { marketName: 'Galaxy A32 5G', brand: 'Samsung' },
  'SM-A315F': { marketName: 'Galaxy A31', brand: 'Samsung' },
  'SM-A217F': { marketName: 'Galaxy A21s', brand: 'Samsung' },
  'SM-A205F': { marketName: 'Galaxy A20', brand: 'Samsung' },
  'SM-A105F': { marketName: 'Galaxy A10', brand: 'Samsung' },
  'SM-A107F': { marketName: 'Galaxy A10s', brand: 'Samsung' },
  'SM-A505F': { marketName: 'Galaxy A50', brand: 'Samsung' },
  'SM-A507FN': { marketName: 'Galaxy A50s', brand: 'Samsung' },
  'SM-A705FN': { marketName: 'Galaxy A70', brand: 'Samsung' },
  'SM-A805F': { marketName: 'Galaxy A80', brand: 'Samsung' },
  'SM-N986B': { marketName: 'Galaxy Note20 Ultra', brand: 'Samsung' },
  'SM-N985F': { marketName: 'Galaxy Note20 Ultra', brand: 'Samsung' },
  'SM-N981B': { marketName: 'Galaxy Note20', brand: 'Samsung' },
  'SM-N980F': { marketName: 'Galaxy Note20', brand: 'Samsung' },
  'SM-N976B': { marketName: 'Galaxy Note10+ 5G', brand: 'Samsung' },
  'SM-N975F': { marketName: 'Galaxy Note10+', brand: 'Samsung' },
  'SM-N970F': { marketName: 'Galaxy Note10', brand: 'Samsung' },
  'SM-N960F': { marketName: 'Galaxy Note9', brand: 'Samsung' },
  'SM-N950F': { marketName: 'Galaxy Note8', brand: 'Samsung' },
  'SM-J730F': { marketName: 'Galaxy J7 Pro', brand: 'Samsung' },
  'SM-J530F': { marketName: 'Galaxy J5 Pro', brand: 'Samsung' },
  'SM-M546B': { marketName: 'Galaxy M54', brand: 'Samsung' },
  'SM-M536B': { marketName: 'Galaxy M53', brand: 'Samsung' },
  'SM-M346B': { marketName: 'Galaxy M34', brand: 'Samsung' },
  'SM-M336B': { marketName: 'Galaxy M33', brand: 'Samsung' },
  'SM-M236B': { marketName: 'Galaxy M23', brand: 'Samsung' },
  'SM-M146B': { marketName: 'Galaxy M14', brand: 'Samsung' },
  'SM-M135F': { marketName: 'Galaxy M13', brand: 'Samsung' },
  'SM-M127F': { marketName: 'Galaxy M12', brand: 'Samsung' },
  'SM-T870': { marketName: 'Galaxy Tab S7', brand: 'Samsung' },
  'SM-T970': { marketName: 'Galaxy Tab S7+', brand: 'Samsung' },
  'SM-X700': { marketName: 'Galaxy Tab S8', brand: 'Samsung' },
  'SM-X800': { marketName: 'Galaxy Tab S8+', brand: 'Samsung' },
  'SM-X900': { marketName: 'Galaxy Tab S8 Ultra', brand: 'Samsung' },

  // ===== TECNO =====
  // Camon 12 / 15 / 16 series
  'CC6': { marketName: 'Camon 12 Air', brand: 'Tecno' },
  'CC7': { marketName: 'Camon 12', brand: 'Tecno' },
  'CC7n': { marketName: 'Camon 12 Pro', brand: 'Tecno' },
  'CC9': { marketName: 'Camon 12 Pro', brand: 'Tecno' },
  'CD6': { marketName: 'Camon 15 Air', brand: 'Tecno' },
  'CD7': { marketName: 'Camon 15', brand: 'Tecno' },
  'CD7n': { marketName: 'Camon 15 Pro', brand: 'Tecno' },
  'CD8': { marketName: 'Camon 15 Premier', brand: 'Tecno' },
  'CE7': { marketName: 'Camon 16', brand: 'Tecno' },
  'CE7j': { marketName: 'Camon 16', brand: 'Tecno' },
  'CE8': { marketName: 'Camon 16 Pro', brand: 'Tecno' },
  'CE9': { marketName: 'Camon 16 Premier', brand: 'Tecno' },
  // Camon 17 series (CG)
  'CG6': { marketName: 'Camon 17', brand: 'Tecno' },
  'CG6j': { marketName: 'Camon 17', brand: 'Tecno' },
  'CG7': { marketName: 'Camon 17P', brand: 'Tecno' },
  'CG7h': { marketName: 'Camon 17P', brand: 'Tecno' },
  'CG7n': { marketName: 'Camon 17P', brand: 'Tecno' },
  'CG8': { marketName: 'Camon 17 Pro', brand: 'Tecno' },
  'CG8h': { marketName: 'Camon 17 Pro', brand: 'Tecno' },
  // Camon 18 series (CH) — THIS IS THE FIX
  'CH6': { marketName: 'Camon 18i', brand: 'Tecno' },
  'CH6n': { marketName: 'Camon 18', brand: 'Tecno' },
  'CH7': { marketName: 'Camon 18T', brand: 'Tecno' },
  'CH7n': { marketName: 'Camon 18P', brand: 'Tecno' },
  'CH9': { marketName: 'Camon 18 Premier', brand: 'Tecno' },
  // Camon 19 series (CI)
  'CI6': { marketName: 'Camon 19 Neo', brand: 'Tecno' },
  'CI6n': { marketName: 'Camon 19', brand: 'Tecno' },
  'CI7': { marketName: 'Camon 19 Pro', brand: 'Tecno' },
  'CI7n': { marketName: 'Camon 19 Pro', brand: 'Tecno' },
  'CI8': { marketName: 'Camon 19 Pro 5G', brand: 'Tecno' },
  'CI9': { marketName: 'Camon 19 Pro 5G', brand: 'Tecno' },
  // Camon 20 series (CK)
  'CK6': { marketName: 'Camon 20', brand: 'Tecno' },
  'CK6n': { marketName: 'Camon 20', brand: 'Tecno' },
  'CK7': { marketName: 'Camon 20 Pro', brand: 'Tecno' },
  'CK7n': { marketName: 'Camon 20 Pro', brand: 'Tecno' },
  'CK8': { marketName: 'Camon 20 Pro 5G', brand: 'Tecno' },
  'CK8n': { marketName: 'Camon 20 Pro 5G', brand: 'Tecno' },
  'CK9': { marketName: 'Camon 20 Premier 5G', brand: 'Tecno' },
  // Camon 30 series (CL)
  'CL6': { marketName: 'Camon 30', brand: 'Tecno' },
  'CL6n': { marketName: 'Camon 30', brand: 'Tecno' },
  'CL7': { marketName: 'Camon 30 Pro', brand: 'Tecno' },
  'CL7n': { marketName: 'Camon 30 Pro 5G', brand: 'Tecno' },
  'CL8': { marketName: 'Camon 30S', brand: 'Tecno' },
  'CL8n': { marketName: 'Camon 30S Pro', brand: 'Tecno' },
  'CL9': { marketName: 'Camon 30 Premier', brand: 'Tecno' },
  // Spark series
  'KE5': { marketName: 'Spark 7', brand: 'Tecno' },
  'KE5k': { marketName: 'Spark 7T', brand: 'Tecno' },
  'KE7': { marketName: 'Spark 7P', brand: 'Tecno' },
  'KF6': { marketName: 'Spark 7P', brand: 'Tecno' },
  'KF6i': { marketName: 'Spark 7i', brand: 'Tecno' },
  'KF6n': { marketName: 'Spark 7 Pro', brand: 'Tecno' },
  'KF7': { marketName: 'Spark 7 Pro', brand: 'Tecno' },
  'KF8': { marketName: 'Spark 8C', brand: 'Tecno' },
  'KG5': { marketName: 'Spark 9', brand: 'Tecno' },
  'KG5j': { marketName: 'Spark 9T', brand: 'Tecno' },
  'KG5q': { marketName: 'Spark 9T', brand: 'Tecno' },
  'KG6': { marketName: 'Spark Go 2023', brand: 'Tecno' },
  'KG6n': { marketName: 'Spark Go 2024', brand: 'Tecno' },
  'KG7': { marketName: 'Spark 9 Pro', brand: 'Tecno' },
  'KH6': { marketName: 'Spark 10C', brand: 'Tecno' },
  'KH6n': { marketName: 'Spark 10', brand: 'Tecno' },
  'KH7': { marketName: 'Spark 10 Pro', brand: 'Tecno' },
  'KI5': { marketName: 'Spark 8', brand: 'Tecno' },
  'KI5k': { marketName: 'Spark 8T', brand: 'Tecno' },
  'KI5q': { marketName: 'Spark 8C', brand: 'Tecno' },
  'KI7': { marketName: 'Spark 8P', brand: 'Tecno' },
  'KI8': { marketName: 'Spark Go 2022', brand: 'Tecno' },
  'KJ5': { marketName: 'Spark 20', brand: 'Tecno' },
  'KJ6': { marketName: 'Spark 20C', brand: 'Tecno' },
  'KJ7': { marketName: 'Spark 20 Pro', brand: 'Tecno' },
  'KJ8': { marketName: 'Spark 20 Pro+', brand: 'Tecno' },
  // Pop series (entry level)
  'BE6': { marketName: 'Pop 4', brand: 'Tecno' },
  'BE8': { marketName: 'Pova', brand: 'Tecno' },
  'BF6': { marketName: 'Pop 5 LTE', brand: 'Tecno' },
  'BF7': { marketName: 'Pop 5', brand: 'Tecno' },
  'BF7n': { marketName: 'Pop 5 Pro', brand: 'Tecno' },
  'BG6': { marketName: 'Pop 6', brand: 'Tecno' },
  'BG6n': { marketName: 'Pop 6 Pro', brand: 'Tecno' },
  'BH7': { marketName: 'Pop 7', brand: 'Tecno' },
  'BH8': { marketName: 'Pop 8', brand: 'Tecno' },
  // Pova series
  'LE7': { marketName: 'Pova 2', brand: 'Tecno' },
  'LE7n': { marketName: 'Pova Neo', brand: 'Tecno' },
  'LF7n': { marketName: 'Pova 2 5G', brand: 'Tecno' },
  'LG6n': { marketName: 'Pova Neo 2', brand: 'Tecno' },
  'LG7n': { marketName: 'Pova 3', brand: 'Tecno' },
  'LG8': { marketName: 'Pova 4', brand: 'Tecno' },
  'LG8n': { marketName: 'Pova 4 Pro', brand: 'Tecno' },
  'LH7': { marketName: 'Pova Neo 3', brand: 'Tecno' },
  'LH7n': { marketName: 'Pova 5', brand: 'Tecno' },
  'LH8': { marketName: 'Pova 5 Pro', brand: 'Tecno' },
  'LH8n': { marketName: 'Pova 5 Pro 5G', brand: 'Tecno' },
  'LI8': { marketName: 'Pova 6', brand: 'Tecno' },
  'LI8n': { marketName: 'Pova 6 Pro', brand: 'Tecno' },
  'LI9': { marketName: 'Pova 6 Neo', brand: 'Tecno' },
  // Phantom series (premium)
  'AD8': { marketName: 'Phantom X', brand: 'Tecno' },
  'AD9': { marketName: 'Phantom V Fold', brand: 'Tecno' },
  'AD9n': { marketName: 'Phantom V Flip', brand: 'Tecno' },
  'AE8': { marketName: 'Phantom V Fold2', brand: 'Tecno' },
  'AE9': { marketName: 'Phantom V Flip2', brand: 'Tecno' },
  'AF8': { marketName: 'Phantom X2', brand: 'Tecno' },
  'AF8n': { marketName: 'Phantom X2 Pro', brand: 'Tecno' },

  // ===== INFINIX =====
  'X6831': { marketName: 'Hot 40 Pro', brand: 'Infinix' },
  'X6837': { marketName: 'Hot 40', brand: 'Infinix' },
  'X6836': { marketName: 'Hot 40i', brand: 'Infinix' },
  'X6826': { marketName: 'Hot 30', brand: 'Infinix' },
  'X6831B': { marketName: 'Hot 30i', brand: 'Infinix' },
  'X6711': { marketName: 'Hot 20', brand: 'Infinix' },
  'X6711B': { marketName: 'Hot 20S', brand: 'Infinix' },
  'X6817': { marketName: 'Hot 20i', brand: 'Infinix' },
  'X6819': { marketName: 'Hot 20 Play', brand: 'Infinix' },
  'X6525': { marketName: 'Hot 12', brand: 'Infinix' },
  'X6525B': { marketName: 'Hot 12i', brand: 'Infinix' },
  'X6817C': { marketName: 'Hot 12 Play', brand: 'Infinix' },
  'X662': { marketName: 'Hot 11', brand: 'Infinix' },
  'X662B': { marketName: 'Hot 11S', brand: 'Infinix' },
  'X6511': { marketName: 'Hot 11 Play', brand: 'Infinix' },
  'X660': { marketName: 'Hot 10', brand: 'Infinix' },
  'X660B': { marketName: 'Hot 10S', brand: 'Infinix' },
  'X689': { marketName: 'Note 12 Pro', brand: 'Infinix' },
  'X689B': { marketName: 'Note 12', brand: 'Infinix' },
  'X670': { marketName: 'Note 11', brand: 'Infinix' },
  'X663': { marketName: 'Note 10', brand: 'Infinix' },
  'X663B': { marketName: 'Note 10 Pro', brand: 'Infinix' },
  'X6833B': { marketName: 'Note 30 Pro', brand: 'Infinix' },
  'X6833': { marketName: 'Note 30', brand: 'Infinix' },
  'X6851': { marketName: 'Note 40 Pro', brand: 'Infinix' },
  'X6850': { marketName: 'Note 40', brand: 'Infinix' },
  'X6610': { marketName: 'Zero 5G', brand: 'Infinix' },
  'X6820': { marketName: 'Zero 20', brand: 'Infinix' },
  'X6821': { marketName: 'Zero Ultra', brand: 'Infinix' },
  'X6835': { marketName: 'Zero 30', brand: 'Infinix' },
  'X6710': { marketName: 'Smart 7', brand: 'Infinix' },
  'X6515': { marketName: 'Smart 6', brand: 'Infinix' },
  'X657C': { marketName: 'Smart 5', brand: 'Infinix' },
  'X6528': { marketName: 'GT 10 Pro', brand: 'Infinix' },
  'X6525D': { marketName: 'Smart 7 Plus', brand: 'Infinix' },
  'X669': { marketName: 'Smart 8', brand: 'Infinix' },
  'X669C': { marketName: 'Smart 8 Plus', brand: 'Infinix' },
  'X6725': { marketName: 'Smart 9', brand: 'Infinix' },
  'X6725B': { marketName: 'Smart 9 HD', brand: 'Infinix' },
  'X6858': { marketName: 'Hot 50 Pro+', brand: 'Infinix' },
  'X6876': { marketName: 'Hot 50 Pro', brand: 'Infinix' },
  'X6875': { marketName: 'Hot 50', brand: 'Infinix' },
  'X6882': { marketName: 'Hot 50i', brand: 'Infinix' },
  'X6731': { marketName: 'Hot 30 Play', brand: 'Infinix' },
  'X6816': { marketName: 'Hot 11 2022', brand: 'Infinix' },
  'X6515B': { marketName: 'Smart 6 HD', brand: 'Infinix' },
  'X657B': { marketName: 'Smart 5A', brand: 'Infinix' },
  'X665': { marketName: 'Note 8', brand: 'Infinix' },
  'X665B': { marketName: 'Note 8i', brand: 'Infinix' },
  'X693': { marketName: 'Note 7', brand: 'Infinix' },
  'X690': { marketName: 'Note 7 Lite', brand: 'Infinix' },
  'X6855': { marketName: 'Note 40 Pro+', brand: 'Infinix' },
  'X6852': { marketName: 'Note 40 Pro 5G', brand: 'Infinix' },
  'X6840': { marketName: 'Zero 40', brand: 'Infinix' },
  'X6841': { marketName: 'Zero 40 5G', brand: 'Infinix' },
  'X6739': { marketName: 'Hot 30i', brand: 'Infinix' },

  // ===== XIAOMI / REDMI / POCO =====
  '23127PN0CG': { marketName: 'Redmi Note 13 Pro+', brand: 'Xiaomi' },
  '2312DRA50G': { marketName: 'Redmi Note 13 Pro', brand: 'Xiaomi' },
  '23106RN0DA': { marketName: 'Redmi Note 13', brand: 'Xiaomi' },
  '22101316G': { marketName: 'Redmi Note 12 Pro+', brand: 'Xiaomi' },
  '22101316I': { marketName: 'Redmi Note 12 Pro', brand: 'Xiaomi' },
  '2209116AG': { marketName: 'Redmi Note 12', brand: 'Xiaomi' },
  '2201116TG': { marketName: 'Redmi Note 11 Pro+', brand: 'Xiaomi' },
  '2201116SG': { marketName: 'Redmi Note 11 Pro', brand: 'Xiaomi' },
  '2201117TG': { marketName: 'Redmi Note 11', brand: 'Xiaomi' },
  '2109106A1G': { marketName: 'Redmi Note 11S', brand: 'Xiaomi' },
  'M2101K7AG': { marketName: 'Redmi Note 10 Pro', brand: 'Xiaomi' },
  'M2101K7BG': { marketName: 'Redmi Note 10 Pro Max', brand: 'Xiaomi' },
  'M2101K6G': { marketName: 'Redmi Note 10', brand: 'Xiaomi' },
  'M2101K7AI': { marketName: 'Redmi Note 10 Pro', brand: 'Xiaomi' },
  'M2006C3MG': { marketName: 'Redmi Note 9', brand: 'Xiaomi' },
  'M2003J15SC': { marketName: 'Redmi Note 9 Pro', brand: 'Xiaomi' },
  '23076RN8DA': { marketName: 'Redmi 12', brand: 'Xiaomi' },
  '23053RN02A': { marketName: 'Redmi 12C', brand: 'Xiaomi' },
  '22120RN86G': { marketName: 'Redmi A2', brand: 'Xiaomi' },
  '22120RN86C': { marketName: 'Redmi A2', brand: 'Xiaomi' },
  '23028RNCAG': { marketName: 'Redmi A2+', brand: 'Xiaomi' },
  '23053RN02I': { marketName: 'Redmi 12C', brand: 'Xiaomi' },
  '23117RA68G': { marketName: 'Redmi 13C', brand: 'Xiaomi' },
  '24076RA15G': { marketName: 'Redmi 13', brand: 'Xiaomi' },
  '2312DRAABG': { marketName: 'Redmi Note 13', brand: 'Xiaomi' },
  '23021RAA2Y': { marketName: 'POCO C55', brand: 'POCO' },
  '23124RN87I': { marketName: 'POCO C65', brand: 'POCO' },
  '220733SFG': { marketName: 'Redmi A1', brand: 'Xiaomi' },
  '23049PCD8G': { marketName: 'POCO F5', brand: 'Xiaomi' },
  '21121210G': { marketName: 'POCO F4', brand: 'Xiaomi' },
  '23013PC75G': { marketName: 'POCO X5 Pro', brand: 'Xiaomi' },
  '22111317PG': { marketName: 'POCO X5', brand: 'Xiaomi' },
  '2207117BPG': { marketName: 'POCO X4 GT', brand: 'Xiaomi' },
  '22041216G': { marketName: 'POCO M5s', brand: 'Xiaomi' },
  '22071219CG': { marketName: 'POCO M5', brand: 'Xiaomi' },
  '23021RAAEG': { marketName: 'POCO M6 Pro', brand: 'Xiaomi' },
  '2311DRK48G': { marketName: 'POCO C65', brand: 'Xiaomi' },
  '2312FPCA4G': { marketName: 'POCO C61', brand: 'Xiaomi' },
  '2311FRSKD6': { marketName: 'Xiaomi 14', brand: 'Xiaomi' },
  '2311FRSKL6': { marketName: 'Xiaomi 14 Pro', brand: 'Xiaomi' },
  '2304FPN6DC': { marketName: 'Xiaomi 13T Pro', brand: 'Xiaomi' },
  '23078PND5G': { marketName: 'Xiaomi 13T', brand: 'Xiaomi' },
  '2210132G': { marketName: 'Xiaomi 13', brand: 'Xiaomi' },
  '2210132C': { marketName: 'Xiaomi 13 Pro', brand: 'Xiaomi' },
  '2203121C': { marketName: 'Xiaomi 12', brand: 'Xiaomi' },
  '2201123G': { marketName: 'Xiaomi 12 Pro', brand: 'Xiaomi' },
  '24129PN74G': { marketName: 'Xiaomi 15', brand: 'Xiaomi' },
  '24129PN74I': { marketName: 'Xiaomi 15', brand: 'Xiaomi' },
  '2410DPN6CG': { marketName: 'Xiaomi 14T Pro', brand: 'Xiaomi' },
  '2407FPN8EG': { marketName: 'Xiaomi 14T', brand: 'Xiaomi' },
  '24094RAD4G': { marketName: 'Redmi Note 14 Pro+', brand: 'Xiaomi' },
  '24090RA29G': { marketName: 'Redmi Note 14 Pro', brand: 'Xiaomi' },
  '24117RK22G': { marketName: 'Redmi Note 14', brand: 'Xiaomi' },
  '24076PN4BG': { marketName: 'POCO F6 Pro', brand: 'Xiaomi' },
  '24069PC21G': { marketName: 'POCO F6', brand: 'Xiaomi' },
  '24049PCD5G': { marketName: 'POCO X6 Pro', brand: 'Xiaomi' },
  '2311DRK48I': { marketName: 'POCO M6 5G', brand: 'Xiaomi' },
  '2404ARN45I': { marketName: 'Redmi 13', brand: 'Xiaomi' },
  '24053PY09I': { marketName: 'Redmi 13C', brand: 'Xiaomi' },
  '23124RA7EO': { marketName: 'Redmi 13C', brand: 'Xiaomi' },
  'M2012K11AG': { marketName: 'Mi 10T Pro', brand: 'Xiaomi' },
  'M2007J3SY': { marketName: 'Mi 10T', brand: 'Xiaomi' },
  'M2002J9G': { marketName: 'Mi 10 Lite', brand: 'Xiaomi' },
  'M2004J19C': { marketName: 'Redmi 9', brand: 'Xiaomi' },
  'M2003J6A1G': { marketName: 'Redmi 9', brand: 'Xiaomi' },
  'M2010J19SG': { marketName: 'Redmi 9T', brand: 'Xiaomi' },
  'M2006C3LG': { marketName: 'Redmi 9A', brand: 'Xiaomi' },
  'M2006C3LII': { marketName: 'Redmi 9A', brand: 'Xiaomi' },
  'M2006C3LVG': { marketName: 'Redmi 9C', brand: 'Xiaomi' },
  'M2101K9AG': { marketName: 'Mi 11 Lite', brand: 'Xiaomi' },
  'M2101K9AI': { marketName: 'Mi 11 Lite', brand: 'Xiaomi' },
  'M2012K11AI': { marketName: 'Mi 11X Pro', brand: 'Xiaomi' },
  'M2011K2G': { marketName: 'Mi 11', brand: 'Xiaomi' },
  'M2102J2SG': { marketName: 'Mi 11 Ultra', brand: 'Xiaomi' },
  'Redmi K20': { marketName: 'Redmi K20', brand: 'Xiaomi' },
  'Redmi K20 Pro': { marketName: 'Redmi K20 Pro', brand: 'Xiaomi' },
  'Mi A3': { marketName: 'Mi A3', brand: 'Xiaomi' },
  'Mi 9T': { marketName: 'Mi 9T', brand: 'Xiaomi' },

  // ===== OPPO =====
  'CPH2581': { marketName: 'Reno 11 Pro', brand: 'OPPO' },
  'CPH2579': { marketName: 'Reno 11', brand: 'OPPO' },
  'CPH2531': { marketName: 'Reno 10 Pro+', brand: 'OPPO' },
  'CPH2525': { marketName: 'Reno 10 Pro', brand: 'OPPO' },
  'CPH2521': { marketName: 'Reno 10', brand: 'OPPO' },
  'CPH2477': { marketName: 'Reno 8 Pro', brand: 'OPPO' },
  'CPH2473': { marketName: 'Reno 8', brand: 'OPPO' },
  'CPH2461': { marketName: 'Reno 8T', brand: 'OPPO' },
  'CPH2363': { marketName: 'Reno 7', brand: 'OPPO' },
  'CPH2371': { marketName: 'Reno 7 Pro', brand: 'OPPO' },
  'CPH2505': { marketName: 'A78', brand: 'OPPO' },
  'CPH2495': { marketName: 'A77s', brand: 'OPPO' },
  'CPH2457': { marketName: 'A77', brand: 'OPPO' },
  'CPH2565': { marketName: 'A58', brand: 'OPPO' },
  'CPH2569': { marketName: 'A38', brand: 'OPPO' },
  'CPH2591': { marketName: 'A18', brand: 'OPPO' },
  'CPH2533': { marketName: 'A17', brand: 'OPPO' },
  'CPH2269': { marketName: 'A16', brand: 'OPPO' },
  'CPH2479': { marketName: 'Find X5 Pro', brand: 'OPPO' },
  'CPH2449': { marketName: 'Find X5', brand: 'OPPO' },
  'CPH2559': { marketName: 'Find N3 Flip', brand: 'OPPO' },

  // ===== REALME =====
  'RMX3761': { marketName: 'Realme 12 Pro+', brand: 'Realme' },
  'RMX3757': { marketName: 'Realme 12 Pro', brand: 'Realme' },
  'RMX3771': { marketName: 'Realme 12', brand: 'Realme' },
  'RMX3630': { marketName: 'Realme 11 Pro+', brand: 'Realme' },
  'RMX3645': { marketName: 'Realme 11 Pro', brand: 'Realme' },
  'RMX3636': { marketName: 'Realme 11', brand: 'Realme' },
  'RMX3563': { marketName: 'Realme 10 Pro+', brand: 'Realme' },
  'RMX3686': { marketName: 'Realme 10 Pro', brand: 'Realme' },
  'RMX3521': { marketName: 'Realme 9 Pro+', brand: 'Realme' },
  'RMX3471': { marketName: 'Realme 9 Pro', brand: 'Realme' },
  'RMX3393': { marketName: 'Realme GT 2 Pro', brand: 'Realme' },
  'RMX3311': { marketName: 'Realme GT Neo 3', brand: 'Realme' },
  'RMX3781': { marketName: 'Realme C67', brand: 'Realme' },
  'RMX3760': { marketName: 'Realme C55', brand: 'Realme' },
  'RMX3624': { marketName: 'Realme C53', brand: 'Realme' },
  'RMX3623': { marketName: 'Realme Narzo 60', brand: 'Realme' },
  'RMX3627': { marketName: 'Realme Narzo 60 Pro', brand: 'Realme' },

  // ===== VIVO =====
  'V2307': { marketName: 'V29', brand: 'Vivo' },
  'V2250': { marketName: 'V27', brand: 'Vivo' },
  'V2246': { marketName: 'V25 Pro', brand: 'Vivo' },
  'V2232': { marketName: 'V25', brand: 'Vivo' },
  'V2202': { marketName: 'V23', brand: 'Vivo' },
  'V2130': { marketName: 'Y22', brand: 'Vivo' },
  'V2207': { marketName: 'Y35', brand: 'Vivo' },
  'V2238': { marketName: 'Y36', brand: 'Vivo' },
  'V2249': { marketName: 'Y56', brand: 'Vivo' },
  'V2234': { marketName: 'Y02', brand: 'Vivo' },
  'V2217': { marketName: 'Y16', brand: 'Vivo' },
  'V2120': { marketName: 'T1', brand: 'Vivo' },
  'V2303': { marketName: 'T2', brand: 'Vivo' },
  'V2310': { marketName: 'X100 Pro', brand: 'Vivo' },
  'V2309': { marketName: 'X100', brand: 'Vivo' },
  'V2254': { marketName: 'X90 Pro', brand: 'Vivo' },

  // ===== GOOGLE PIXEL =====
  'Pixel 9 Pro XL': { marketName: 'Pixel 9 Pro XL', brand: 'Google' },
  'Pixel 9 Pro': { marketName: 'Pixel 9 Pro', brand: 'Google' },
  'Pixel 9': { marketName: 'Pixel 9', brand: 'Google' },
  'Pixel 8 Pro': { marketName: 'Pixel 8 Pro', brand: 'Google' },
  'Pixel 8a': { marketName: 'Pixel 8a', brand: 'Google' },
  'Pixel 8': { marketName: 'Pixel 8', brand: 'Google' },
  'Pixel 7 Pro': { marketName: 'Pixel 7 Pro', brand: 'Google' },
  'Pixel 7a': { marketName: 'Pixel 7a', brand: 'Google' },
  'Pixel 7': { marketName: 'Pixel 7', brand: 'Google' },
  'Pixel 6 Pro': { marketName: 'Pixel 6 Pro', brand: 'Google' },
  'Pixel 6a': { marketName: 'Pixel 6a', brand: 'Google' },
  'Pixel 6': { marketName: 'Pixel 6', brand: 'Google' },

  // ===== ONEPLUS =====
  'CPH2609': { marketName: 'OnePlus 12', brand: 'OnePlus' },
  'CPH2451': { marketName: 'OnePlus 11', brand: 'OnePlus' },
  'NE2215': { marketName: 'OnePlus 10 Pro', brand: 'OnePlus' },
  'LE2125': { marketName: 'OnePlus 9 Pro', brand: 'OnePlus' },
  'LE2115': { marketName: 'OnePlus 9', brand: 'OnePlus' },
  'IN2025': { marketName: 'OnePlus 8 Pro', brand: 'OnePlus' },
  'IN2015': { marketName: 'OnePlus 8', brand: 'OnePlus' },
  'IN2023': { marketName: 'OnePlus 8T', brand: 'OnePlus' },
  'AC2003': { marketName: 'OnePlus Nord', brand: 'OnePlus' },
  'IV2201': { marketName: 'OnePlus Nord 2T', brand: 'OnePlus' },
  'CPH2493': { marketName: 'OnePlus Nord CE 3', brand: 'OnePlus' },
  'CPH2467': { marketName: 'OnePlus Nord CE 2 Lite', brand: 'OnePlus' },
  'CPH2469': { marketName: 'OnePlus Nord N30', brand: 'OnePlus' },
  'CPH2515': { marketName: 'OnePlus Nord N20 SE', brand: 'OnePlus' },

  // ===== HUAWEI =====
  'VOG-L29': { marketName: 'P30 Pro', brand: 'Huawei' },
  'VOG-L09': { marketName: 'P30 Pro', brand: 'Huawei' },
  'ELE-L29': { marketName: 'P30', brand: 'Huawei' },
  'ELS-NX9': { marketName: 'P40 Pro', brand: 'Huawei' },
  'ELS-N39': { marketName: 'P40 Pro', brand: 'Huawei' },
  'ANA-NX9': { marketName: 'P40', brand: 'Huawei' },
  'ANA-LX4': { marketName: 'P40', brand: 'Huawei' },
  'JNY-LX1': { marketName: 'P40 Lite', brand: 'Huawei' },
  'STK-LX1': { marketName: 'Honor 9X', brand: 'Huawei' },
  'MAR-LX1A': { marketName: 'P30 Lite', brand: 'Huawei' },
  'YAL-L21': { marketName: 'Nova 5T', brand: 'Huawei' },

  // ===== MOTOROLA =====
  'XT2347-2': { marketName: 'Edge 40 Pro', brand: 'Motorola' },
  'XT2343-2': { marketName: 'Edge 40', brand: 'Motorola' },
  'XT2301-4': { marketName: 'Edge 30 Ultra', brand: 'Motorola' },
  'XT2243-1': { marketName: 'Moto G84', brand: 'Motorola' },
  'XT2347-4': { marketName: 'Moto G73', brand: 'Motorola' },
  'XT2237-2': { marketName: 'Moto G72', brand: 'Motorola' },
  'XT2235-2': { marketName: 'Moto G62', brand: 'Motorola' },
  'XT2225-1': { marketName: 'Moto G52', brand: 'Motorola' },
  'XT2223-1': { marketName: 'Moto G42', brand: 'Motorola' },
  'XT2341-3': { marketName: 'Moto G14', brand: 'Motorola' },
  'XT2345-3': { marketName: 'Moto G24', brand: 'Motorola' },
  'XT2339-5': { marketName: 'Moto G34', brand: 'Motorola' },
  'XT2331-1': { marketName: 'Moto G Power 2023', brand: 'Motorola' },

  // ===== NOKIA =====
  'TA-1506': { marketName: 'Nokia G42', brand: 'Nokia' },
  'TA-1495': { marketName: 'Nokia G22', brand: 'Nokia' },
  'TA-1489': { marketName: 'Nokia C32', brand: 'Nokia' },
  'TA-1469': { marketName: 'Nokia G60', brand: 'Nokia' },
  'TA-1401': { marketName: 'Nokia G21', brand: 'Nokia' },
  'TA-1365': { marketName: 'Nokia G20', brand: 'Nokia' },

  // ===== NOTHING =====
  'A063': { marketName: 'Nothing Phone (1)', brand: 'Nothing' },
  'A065': { marketName: 'Nothing Phone (2)', brand: 'Nothing' },
  'A142': { marketName: 'Nothing Phone (2a)', brand: 'Nothing' },

  // ===== ITEL =====
  'W6006': { marketName: 'Itel S23+', brand: 'Itel' },
  'W6003': { marketName: 'Itel S23', brand: 'Itel' },
  'W6502': { marketName: 'Itel A60s', brand: 'Itel' },
  'W6501': { marketName: 'Itel A60', brand: 'Itel' },
  'P662L': { marketName: 'Itel P40', brand: 'Itel' },
  'P661W': { marketName: 'Itel P38', brand: 'Itel' },

  // ===== HONOR =====
  'CRT-LX1': { marketName: 'Honor Magic5 Pro', brand: 'Honor' },
  'REA-NX9': { marketName: 'Honor 90', brand: 'Honor' },
  'CRT-LX3': { marketName: 'Honor Magic5 Lite', brand: 'Honor' },
  'ANY-LX1': { marketName: 'Honor X8', brand: 'Honor' },
  'FNE-NX9': { marketName: 'Honor X7a', brand: 'Honor' },

  // ===== SONY =====
  'XQ-DQ72': { marketName: 'Xperia 1 V', brand: 'Sony' },
  'XQ-CQ72': { marketName: 'Xperia 1 IV', brand: 'Sony' },
  'XQ-DQ54': { marketName: 'Xperia 5 V', brand: 'Sony' },
  'XQ-CQ54': { marketName: 'Xperia 5 IV', brand: 'Sony' },
  'XQ-DC72': { marketName: 'Xperia 10 V', brand: 'Sony' },
  'XQ-CC72': { marketName: 'Xperia 10 IV', brand: 'Sony' },

  // ===== LG =====
  'LM-V510': { marketName: 'LG V60 ThinQ', brand: 'LG' },
  'LM-G900': { marketName: 'LG Velvet', brand: 'LG' },
  'LM-K520': { marketName: 'LG K52', brand: 'LG' },
  'LM-Q730': { marketName: 'LG Stylo 6', brand: 'LG' },

  // ===== ASUS =====
  'ASUS_AI2302': { marketName: 'ROG Phone 7', brand: 'ASUS' },
  'ASUS_AI2401': { marketName: 'Zenfone 11 Ultra', brand: 'ASUS' },
  'ASUS_AI2205': { marketName: 'Zenfone 9', brand: 'ASUS' },
  'ASUS_AI2202': { marketName: 'ROG Phone 6', brand: 'ASUS' },
};

export function lookupModel(rawModel: string): ModelEntry | null {
  if (!rawModel) return null;

  const direct = db[rawModel];
  if (direct) return direct;

  const upper = rawModel.toUpperCase();
  for (const [key, val] of Object.entries(db)) {
    if (key.toUpperCase() === upper) return val;
  }

  const noSuffix = rawModel.replace(/\/.*$/, '').trim();
  if (noSuffix !== rawModel) {
    const found = db[noSuffix];
    if (found) return found;
  }

  for (const [key, val] of Object.entries(db)) {
    if (rawModel.startsWith(key) || rawModel.includes(key)) return val;
  }

  return null;
}

export function identifyBrand(model: string): string {
  const m = model.toUpperCase();
  if (/^SM-/.test(m)) return 'Samsung';
  if (/^PIXEL/i.test(m)) return 'Google';
  if (/^(CC|CD|CE|CG|CH|CI|CK|CL|KE|KF|KG|KH|KI|KJ|BE|BF|BG|BH|LE|LF|LG|LH|LI|AD|AE|AF)[0-9]/i.test(m)) return 'Tecno';
  if (/^X6[0-9]{3}/i.test(m)) return 'Infinix';
  if (/^(2[0-9]{7}|M2[0-9]{6})/i.test(m)) return 'Xiaomi';
  if (/^CPH/i.test(m)) return 'OPPO/OnePlus';
  if (/^RMX/i.test(m)) return 'Realme';
  if (/^V[0-9]{4}/i.test(m)) return 'Vivo';
  if (/^XT[0-9]{4}/i.test(m)) return 'Motorola';
  if (/^TA-/i.test(m)) return 'Nokia';
  if (/^(NE|LE|IN|AC|IV)[0-9]{4}/i.test(m)) return 'OnePlus';
  if (/^(VOG|ELE|ELS|ANA|JNY|MAR|YAL|STK)/i.test(m)) return 'Huawei';
  if (/^(CRT|REA|ANY|FNE)/i.test(m)) return 'Honor';
  if (/^A0[0-9]{2}/i.test(m)) return 'Nothing';
  if (/^(W[0-9]{4}|P[0-9]{3})/i.test(m)) return 'Itel';
  if (/^XQ-/i.test(m)) return 'Sony';
  if (/^LM-/i.test(m)) return 'LG';
  if (/^ASUS/i.test(m)) return 'ASUS';
  if (/^ZS[0-9]{3}/i.test(m)) return 'ASUS';
  return 'Android';
}
